name: Create Free Azure VM and Storage

on:
  workflow_dispatch:

permissions:
  id-token: write  
  contents: read    

jobs:
  create-free-resources:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: SERVICE_PRINCIPAL
        allow-no-subscriptions: true  

    - name: Set Azure Subscription
      run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Create Resource Group
      run: |
        az group create --name MyTestResourceGroup --location eastus --only-show-errors || echo "Resource group already exists."

    - name: Create Free-tier Azure Storage Account
      run: |
        az storage account create \
          --name mystoragefree12345 \
          --resource-group MyTestResourceGroup \
          --location eastus \
          --sku Standard_LRS --only-show-errors || echo "Storage account might already exist."

    - name: Create Free-tier Ubuntu Virtual Machine
      run: |
        az vm create \
          --resource-group MyTestResourceGroup \
          --name MyVM \
          --image UbuntuLTS \
          --size Standard_B1s \
          --admin-username azureuser \
          --generate-ssh-keys --only-show-errors || echo "VM might already exist."

    - name: Get VM Public IP
      run: |
        az vm list-ip-addresses --name MyVM --resource-group MyTestResourceGroup --output table --only-show-errors || echo "Failed to retrieve VM IP."
