name: Create Free Azure VM

on:
  workflow_dispatch:  # Manual trigger

jobs:
  create-free-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Use GitHub Secret

    - name: Create Resource Group
      run: |
        az group create --name MyTestresourcegroup --location eastus

    - name: Create Free-tier Ubuntu Virtual Machine
      run: |
        az vm create \
          --resource-group MyTestresourcegroup \
          --name testvm \
          --image UbuntuLTS \
          --size Standard_B1s \
          --admin-username azureuser \
          --generate-ssh-keys \
          --public-ip-sku Basic

    - name: Get VM Public IP
      run: |
        az vm list-ip-addresses --name testvm --resource-group MyTestresourcegroup --output table

